- name: Install mineaft server
  hosts: all
  tasks:
    - name: install docker and docker-compose
      package:
        name:
          - docker.io
          - docker-compose

    - name: create /minecraft
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - { "/minecraft" }
        - { "/minecraft/data" }

    - name: Copy docker-compose
      copy:
        src: docker-compose.yml
        dest: /minecraft/
        
    - name: deploy minecraft server with docker
      community.docker.docker_compose:
        project_src: /minecraft
        state: present
      
