- name: Playbook to deploy python app - my-app
  hosts: all
  tasks:
    - name: check my-app dependencies ar installed
      package:
        name: python3-flask

    - name: Check my-app dire exist
      file:
        path: /home/vagrant/my-app
        state: directory

    - name: Copy my-app source
      copy:
        src: ./my-app/app.py
        dest: /home/vagrant/my-app/

    - name: Copy my-app unit file
      copy:
        src: ./my-app.service
        dest: /etc/systemd/system/

    - name: Reload systemd after adding my-app unit
      systemd:
        daemon_reload: true

    - name: 
      service:
        name: my-app
        state: started
